package generator

import (
	"go/ast"
)

// addComment adds a comment at the beginning of
// the parsed ast file to point out that the file
// has been generated by a compiler
func addComment(node *ast.File) {
	// Should be handled more properly, especially
	// position, but this is held back by
	// issues such as golang/go#20744
	node.Comments = append([]*ast.CommentGroup{
		&ast.CommentGroup{
			List: []*ast.Comment{
				&ast.Comment{
					Slash: node.Imports[0].Pos(),
					Text:  "/* This code is auto-generated; DO NOT EDIT */",
				},
			},
		},
	}, node.Comments...)
}